version: 2.1

jobs:
  test:
    parameters:
      python-version:
        type: string

    docker:
      - image: cimg/python:<< parameters.python-version >>

    steps:
      - checkout

      - run:
          name: Show Python version
          command: python --version

      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip

      - run:
          name: Install package with development dependencies
          command: python -m pip install -e ".[dev]"

      - run:
          name: Run pytest
          command: python -m pytest tests -q

      - run:
          name: Run coverage
          command: python -m pytest tests -q --cov=src --cov-report=term-missing

workflows:
  test-python:
    jobs:
      - test:
          name: test-python-3-10
          python-version: "3.10"

      - test:
          name: test-python-3-11
          python-version: "3.11"
