"""Exploratory inspection report for registral-regression fixtures (Phase 1, qualitative)."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from registral_dispersion.concentration_map import build_registral_concentration_matrix
from registral_dispersion.observation import OBSERVATION_MODE_EVENT_BOUNDARIES
from registral_dispersion.profiles import ANALYSIS_PROFILE_OCCUPIED_SPACE
from registral_dispersion.service import run_registral_dispersion_analysis

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "fixtures" / "registral_regression"
REPORTS = ROOT / "reports"

ANALYSIS_PARAMS = {
    "observation_mode": OBSERVATION_MODE_EVENT_BOUNDARIES,
    "analysis_profile": ANALYSIS_PROFILE_OCCUPIED_SPACE,
    "register_low": "A0",
    "register_high": "C8",
    "time_step": 0.25,
    "window_size": 4.0,
    "tie_policy": "as_imported",
}


def _finite_spans(results: dict) -> list[float]:
    spans = np.asarray(results["registral_span"], dtype=float)
    return [float(x) for x in spans if np.isfinite(x)]


def _row_summary(results: dict) -> list[dict]:
    rows = []
    n = len(results["t"])
    for i in range(n):
        span = float(results["registral_span"][i])
        if not np.isfinite(span):
            continue
        rows.append(
            {
                "t": float(results["t"][i]),
                "registral_span": span,
                "mean_pairwise_registral_distance": float(results["mean_pairwise_registral_distance"][i]),
                "occupancy_entropy": float(results["occupancy_entropy"][i]),
                "active_note_count": int(results["active_note_count"][i]),
            }
        )
    return rows


def _concentration_location(path: Path) -> dict:
    bundle = build_registral_concentration_matrix(
        str(path),
        21.0,
        108.0,
        time_bin_size=1.0,
        concentration_mode="unique_pitch_heights",
    )
    mat = np.asarray(bundle["matrix"], dtype=float)
    mids = np.asarray(bundle["pitch_midi"], dtype=int)
    active = mids[np.any(mat > 0, axis=1)]
    if active.size == 0:
        return {"mean_active_midi": None, "min_active_midi": None, "max_active_midi": None}
    weights = mat[np.any(mat > 0, axis=1)].sum(axis=1)
    mean_midi = float(np.average(active, weights=weights))
    return {
        "mean_active_midi": mean_midi,
        "min_active_midi": int(active.min()),
        "max_active_midi": int(active.max()),
    }


def inspect_fixture(path: Path) -> dict:
    out = run_registral_dispersion_analysis(str(path), ANALYSIS_PARAMS)
    if out.get("error"):
        return {"fixture": path.name, "error": out["error"]}
    results = out["results"]
    spans = _finite_spans(results)
    return {
        "fixture": path.stem,
        "path": str(path.relative_to(ROOT.parent)),
        "rows": _row_summary(results),
        "span_min": min(spans) if spans else None,
        "span_max": max(spans) if spans else None,
        "concentration": _concentration_location(path),
    }


def build_report() -> dict:
    entries = []
    for path in sorted(FIXTURES.glob("*.musicxml")):
        entries.append(inspect_fixture(path))
    return {
        "phase": "1_qualitative",
        "analysis_params": ANALYSIS_PARAMS,
        "fixtures": entries,
        "note": "Exploratory only; not golden regression baselines.",
    }


def write_markdown(report: dict, path: Path) -> None:
    lines = [
        "# Registral regression fixture inspection (Phase 1)",
        "",
        "Exploratory report generated by `corpus/scripts/inspect_registral_regression.py`.",
        "Values are **not** strict golden references.",
        "",
        "## Analysis parameters",
        "",
        "```json",
        json.dumps(report["analysis_params"], indent=2),
        "```",
        "",
        "## Fixture summaries",
        "",
    ]
    for entry in report["fixtures"]:
        lines.append(f"### `{entry['fixture']}`")
        if entry.get("error"):
            lines.append(f"- **Error:** {entry['error']}")
            lines.append("")
            continue
        lines.append(f"- span range: {entry['span_min']} … {entry['span_max']}")
        loc = entry["concentration"]
        lines.append(
            f"- concentration map (active MIDI): mean={loc['mean_active_midi']}, "
            f"min={loc['min_active_midi']}, max={loc['max_active_midi']}"
        )
        lines.append("- per-row metrics:")
        for row in entry["rows"]:
            lines.append(
                f"  - t={row['t']:.2f}: span={row['registral_span']:.1f}, "
                f"pairwise={row['mean_pairwise_registral_distance']:.2f}, "
                f"entropy={row['occupancy_entropy']:.3f}, n={row['active_note_count']}"
            )
        lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    REPORTS.mkdir(parents=True, exist_ok=True)
    report = build_report()
    json_path = REPORTS / "registral_regression_inspection.json"
    md_path = REPORTS / "registral_regression_inspection.md"
    json_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    write_markdown(report, md_path)
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
